#!/usr/bin/env node
/**
 * Reads the local SQLite mart at .local/rideoasis-map.db and emits a SQL file
 * suitable for `wrangler d1 execute` / `wrangler d1 import` to populate the
 * Cloudflare D1 instance backing the Workers deployment.
 *
 * Output is written as multi-row `INSERT INTO ... VALUES (...), (...);` batches
 * (default 200 rows per statement) so the upload is a few hundred small SQL
 * commands instead of tens of thousands of one-row inserts.
 */

const fs = require('node:fs');
const path = require('node:path');
const { DatabaseSync } = require('node:sqlite');

const DEFAULT_INPUT = '.local/rideoasis-map.db';
const DEFAULT_OUTPUT = 'cloudflare/seed.sql';
const DEFAULT_BATCH = 200;
const COLUMNS = [
  'supply_point_id',
  'chain',
  'store_id',
  'name',
  'lat',
  'lng',
  'address_norm',
  'geocode_level',
  'geocode_point_level',
  'source_url',
  'updated_at'
];

function printHelp() {
  console.log([
    'Usage:',
    '  node scripts/export_d1_seed.js [--input .local/rideoasis-map.db] [--output cloudflare/seed.sql] [--batch 200]',
    '',
    'Reads supply_points rows from the local SQLite mart and emits batched INSERT',
    'statements ready for `wrangler d1 execute --file` against the rideoasis-supply-points D1 database.'
  ].join('\n'));
}

function parseArgs(argv) {
  const args = {
    input: DEFAULT_INPUT,
    output: DEFAULT_OUTPUT,
    batch: DEFAULT_BATCH,
    help: false
  };
  for (let i = 2; i < argv.length; i += 1) {
    const token = argv[i];
    if (token === '--input') {
      args.input = argv[++i];
    } else if (token === '--output') {
      args.output = argv[++i];
    } else if (token === '--batch') {
      const next = Number(argv[++i]);
      if (!Number.isInteger(next) || next <= 0) {
        throw new Error('--batch must be a positive integer');
      }
      args.batch = next;
    } else if (token === '--help' || token === '-h') {
      args.help = true;
    } else {
      throw new Error(`unknown arg: ${token}`);
    }
  }
  return args;
}

/** Escapes a JS value into a SQL literal for sqlite/D1 (TEXT or REAL or NULL). */
function sqlLiteral(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) return 'NULL';
    return String(value);
  }
  return `'${String(value).replaceAll("'", "''")}'`;
}

function buildInsertHeader() {
  return `INSERT INTO supply_points (${COLUMNS.join(', ')}) VALUES`;
}

function buildRowTuple(row) {
  return `(${COLUMNS.map((col) => sqlLiteral(row[col])).join(', ')})`;
}

function main(argv) {
  let args;
  try {
    args = parseArgs(argv);
  } catch (error) {
    console.error(error.message);
    printHelp();
    process.exit(1);
  }
  if (args.help) {
    printHelp();
    return;
  }

  const inputPath = path.resolve(args.input);
  if (!fs.existsSync(inputPath)) {
    console.error(`input not found: ${inputPath}`);
    process.exit(2);
  }
  const outputPath = path.resolve(args.output);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });

  const database = new DatabaseSync(inputPath, { readOnly: true });
  const rows = database.prepare(`SELECT ${COLUMNS.join(', ')} FROM supply_points ORDER BY supply_point_id`).all();

  const stream = fs.createWriteStream(outputPath, { encoding: 'utf8' });
  stream.write(`-- Auto-generated by scripts/export_d1_seed.js (rows: ${rows.length}, batch: ${args.batch})\n`);
  stream.write(`-- Apply with: wrangler d1 execute rideoasis-supply-points --file=${args.output} --remote\n\n`);

  for (let start = 0; start < rows.length; start += args.batch) {
    const chunk = rows.slice(start, start + args.batch);
    stream.write(buildInsertHeader());
    stream.write('\n  ');
    stream.write(chunk.map(buildRowTuple).join(',\n  '));
    stream.write(';\n\n');
  }

  stream.end();
  console.log(`wrote ${rows.length} rows in ${Math.ceil(rows.length / args.batch)} batches to ${outputPath}`);
}

if (require.main === module) {
  main(process.argv);
}

module.exports = { parseArgs, sqlLiteral, buildInsertHeader, buildRowTuple, COLUMNS };
